# Clock
- ros_topic_name: "clock"
  gz_topic_name: "clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS
# Servo move:
- ros_topic_name: "g_mov_servo_conn_joint/cmd_pos"
  gz_topic_name: "/model/g_mov_module/joint/g_mov_servo_conn_joint/0/cmd_pos"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ