<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!--///////////////////// GENERIC SPACERS MACROS ///////////////////////-->
    <!-- ...................... Single spacers ............................ -->
    <xacro:macro name="generic_spacer"
            params="id parent element front side x y z">
        <link name="${id}_${element}_${front}${side}">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
            <mesh filename="package://g_mov_description/meshes/spacer_${id}.stl" 
                scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="Brass"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
            <mesh filename="package://g_mov_description/meshes/spacer_${id}.stl" 
                scale="0.001 0.001 0.001"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0 " rpy="0 0 0"/>
            <xacro:if value="${id == 'm3x20'}">
                <mass value="0.0024"/>
                <inertia ixx="8.5251996963501e-08" ixy="0" ixz="0"
                        iyy="8.648216387229408e-08" iyz="0"
                        izz="1.333016690879308e-08"/>
            </xacro:if>
            <xacro:if value="${id == 'm3x10'}">
                <mass value="0.0012"/>
                <inertia ixx="1.2825999244689955e-08" ixy="0" ixz="0"
                        iyy="1.3441082699086494e-08" iyz="0"
                        izz="6.66508345439654e-09"/>
            </xacro:if>
            <xacro:if value="${id == 'm3x6'}">
                <mass value="0.00072"/>
                <inertia ixx="3.9036000675201425e-09" ixy="0" ixz="0"
                        iyy=".272650140158067e-09" iyz="0"
                        izz="3.9990500726379235e-09"/>
            </xacro:if>
        </inertial>
        </link>
        <joint name="${id}_${element}_${front}${side}_joint" type="fixed">
            <parent link="${parent}"/>
            <child link="${id}_${element}_${front}${side}"/>
            <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
        </joint>
        <xacro:if value="${gazebo}">
            <gazebo reference="${id}_${element}_${front}${side}">
                <mu1>1.0</mu1>
                <mu2>1.0</mu2>
            </gazebo>
        </xacro:if>
    </xacro:macro>
    
    <!-- 4 symetric hex spacers by considering x/y axis -->
    <xacro:macro name="x4xgeneric_spacer" 
                params="id element parent offset_x offset_y x y z">
        <xacro:generic_spacer id="${id}" parent="${parent}" element="${element}" 
            front="f" side="r" x="${x + offset_x}" y="${y - offset_y}" z="${z}"/>
        <xacro:generic_spacer id="${id}" parent="${parent}" element="${element}" 
            front="f" side="l" x="${x + offset_x}" y="${y + offset_y}" z="${z}"/>
        <xacro:generic_spacer id="${id}" parent="${parent}" element="${element}" 
            front="r" side="r" x="${x - offset_x}" y="${y + offset_y}" z="${z}"/>
        <xacro:generic_spacer id="${id}" parent="${parent}" element="${element}" 
            front="r" side="l" x="${x - offset_x}" y="${y - offset_y}" z="${z}"/>
    </xacro:macro>

    <!-- /////////////////////// Sensors macros ////////////////////////// -->
    <xacro:macro name="add_cam_links" params="x y z R P Y parent">
        <!-- ................... Camera sensors links .................. -->
        <link name="g_mov_cam_link"/>

        <joint name="g_mov_cam_joint" type="fixed">
            <origin xyz="${x} ${y} ${z}" rpy="${-pi/2} 0 0"/>
            <parent link="${parent}"/>
            <child link="g_mov_cam_link"/>
        </joint>

        <link name="g_mov_cam_link_optical"/>

        <joint name="g_mov_optical_joint" type="fixed">
            <origin xyz="0 0 0" rpy="${R} ${P} ${Y}"/>
            <parent link="g_mov_cam_link"/>
            <child link="g_mov_cam_link_optical"/>
        </joint>
    </xacro:macro>

    <!-- //////////////////////////// Assemblys macros ////////////////////////// -->
    <xacro:macro name="g_mov_assem" params="parent spacer offset x y z joint_prefix">
        <!-- Properties -->
        <xacro:property name="heigh_level" value="0.005"/>
        <xacro:if value="${spacer == 'm3x20'}">
            <xacro:property name="heigh_level" value="0.020"/>
        </xacro:if>
        <xacro:if value="${spacer == 'm3x10'}">
            <xacro:property name="heigh_level" value="0.010"/>
        </xacro:if>
        <xacro:if value="${spacer == 'm3x6'}">
            <xacro:property name="heigh_level" value="0.006"/>
        </xacro:if>

        <!-- Spacers -->
        <xacro:x4xgeneric_spacer id="${spacer}" element="${parent}" parent="${parent}"
            offset_x="${0.06365/2}" offset_y="${offset}" x="${x}" y="${y}" z="${z}"/>

        <!-- Link Accel -->
        <link name="accel_base">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
            <mesh filename="package://g_mov_description/meshes/accel_base.stl" 
                scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="PLAGray"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
            <mesh filename="package://g_mov_description/meshes/accel_base.stl" 
                scale="0.001 0.001 0.001"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0 " rpy="0 0 0"/>
                <mass value="0.008"/>
                <inertia ixx="1.1233333333333333e-06" ixy="0" ixz="0"
                        iyy="3.458666666666666e-06" iyz="0"
                        izz="4.576666666666666e-06"/>
        </inertial>
        </link>
        <joint name="accel_base_joint" type="fixed">
            <parent link="${parent}"/>
            <child link="accel_base"/>
            <origin xyz="${x} ${y} ${z + heigh_level}" rpy="0 0 0"/>
        </joint>
        <xacro:if value="${gazebo}">
            <gazebo reference="accel_base">
                <mu1>1.0</mu1>
                <mu2>1.0</mu2>
            </gazebo>
        </xacro:if>

        <!-- Link Accel -->
        <link name="accel">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
            <mesh filename="package://g_mov_description/meshes/accel.stl" 
                scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="ArduinoBlue"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
            <mesh filename="package://g_mov_description/meshes/accel.stl" 
                scale="0.001 0.001 0.001"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0 " rpy="0 0 0"/>
                <mass value="0.009"/>
                <inertia ixx="4.064043630409241e-07" ixy="0" ixz="0"
                        iyy="2.879643941116337e-07" iyz="0"
                        izz="5.367750071525579e-07"/>
        </inertial>
        </link>
        <joint name="accel_joint" type="fixed">
            <parent link="accel_base"/>
            <child link="accel"/>
            <origin xyz="0.00025 0 0.00175" rpy="0 0 0"/>
        </joint>
        <xacro:if value="${gazebo}">
            <gazebo reference="accel">
                <mu1>1.0</mu1>
                <mu2>1.0</mu2>
            </gazebo>
        </xacro:if>

        <link name="imu"/>
        <joint name="imu_joint" type="fixed">
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <parent link="accel"/>
            <child link="imu"/>
        </joint>
        <xacro:if value="${gazebo}">
            <gazebo>
                <plugin
                    filename="gz-sim-imu-system"
                    name="gz::sim::systems::Imu">
                </plugin>
            </gazebo>
            <gazebo reference="imu">
                <sensor name="imu_sensor" type="imu">
                    <always_on>1</always_on>
                    <update_rate>50</update_rate>
                    <imu>
                    <enable_orientation>true</enable_orientation>
                    <angular_velocity>
                        <x>
                        <noise type="gaussian">
                            <mean>0</mean>
                            <stddev>0.009</stddev>
                            <bias_mean>0.00075</bias_mean>
                            <bias_stddev>0.005</bias_stddev>
                            <dynamic_bias_stddev>0.00002</dynamic_bias_stddev>
                            <dynamic_bias_correlation_time>400.0</dynamic_bias_correlation_time>
                            <precision>0.00025</precision>
                        </noise>
                        </x>
                        <y>
                        <noise type="gaussian">
                            <mean>0</mean>
                            <stddev>0.009</stddev>
                            <bias_mean>0.00075</bias_mean>
                            <bias_stddev>0.005</bias_stddev>
                            <dynamic_bias_stddev>0.00002</dynamic_bias_stddev>
                            <dynamic_bias_correlation_time>400.0</dynamic_bias_correlation_time>
                            <precision>0.00025</precision>
                        </noise>
                        </y>
                        <z>
                        <noise type="gaussian">
                            <mean>0</mean>
                            <stddev>0.009</stddev>
                            <bias_mean>0.00075</bias_mean>
                            <bias_stddev>0.005</bias_stddev>
                            <dynamic_bias_stddev>0.00002</dynamic_bias_stddev>
                            <dynamic_bias_correlation_time>400.0</dynamic_bias_correlation_time>
                            <precision>0.00025</precision>
                        </noise>
                        </z>
                    </angular_velocity>
                    <linear_acceleration>
                        <x>
                        <noise type="gaussian">
                            <mean>0</mean>
                            <stddev>0.021</stddev>
                            <bias_mean>0.05</bias_mean>
                            <bias_stddev>0.0075</bias_stddev>
                            <dynamic_bias_stddev>0.000375</dynamic_bias_stddev>
                            <dynamic_bias_correlation_time>175.0</dynamic_bias_correlation_time>
                            <precision>0.005</precision>
                        </noise>
                        </x>
                        <y>
                        <noise type="gaussian">
                            <mean>0</mean>
                            <stddev>0.021</stddev>
                            <bias_mean>0.05</bias_mean>
                            <bias_stddev>0.0075</bias_stddev>
                            <dynamic_bias_stddev>0.000375</dynamic_bias_stddev>
                            <dynamic_bias_correlation_time>175.0</dynamic_bias_correlation_time>
                            <precision>0.005</precision>
                        </noise>
                        </y>
                        <z>
                        <noise type="gaussian">
                            <mean>0</mean>
                            <stddev>0.021</stddev>
                            <bias_mean>0.05</bias_mean>
                            <bias_stddev>0.0075</bias_stddev>
                            <dynamic_bias_stddev>0.000375</dynamic_bias_stddev>
                            <dynamic_bias_correlation_time>175.0</dynamic_bias_correlation_time>
                            <precision>0.005</precision>
                        </noise>
                        </z>
                    </linear_acceleration>
                    </imu>
                </sensor>
            </gazebo>
        </xacro:if>

        <!-- Spacers -->
        <xacro:x4xgeneric_spacer id="${spacer}" element="accel_base" parent="accel_base"
            offset_x="${0.06365/2}" offset_y="${offset}" x="0" y="0" z="0.00175"/>

        <!-- Link servo_base -->
        <link name="servo_base">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
            <mesh filename="package://g_mov_description/meshes/servo_base.stl" 
                scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="PLAGray"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
            <mesh filename="package://g_mov_description/meshes/servo_base.stl" 
                scale="0.001 0.001 0.001"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0 " rpy="0 0 0"/>
                <mass value="0.012"/>
                <inertia ixx="2.21e-06" ixy="0" ixz="0"
                        iyy="5.713e-06" iyz="0"
                        izz="6.8649999999999995e-06"/>
        </inertial>
        </link>
        <joint name="servo_base_joint" type="fixed">
            <parent link="accel_base"/>
            <child link="servo_base"/>
            <origin xyz="0.00025 0 ${0.00175+heigh_level}" rpy="0 0 0"/>
        </joint>
        <xacro:if value="${gazebo}">
            <gazebo reference="servo_base">
                <mu1>1.0</mu1>
                <mu2>1.0</mu2>
            </gazebo>
        </xacro:if>

        <!-- Link servo -->
        <link name="servo">
        <visual>
            <origin xyz="0 0 0" rpy="${-pi/2} 0 0"/>
            <geometry>
            <mesh filename="package://g_mov_description/meshes/servo_mg996r.stl" 
                scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="SoftBlack"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${-pi/2} 0 0"/>
            <geometry>
            <mesh filename="package://g_mov_description/meshes/servo_mg996r.stl" 
                scale="0.001 0.001 0.001"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0 " rpy="${pi/2} 0 0"/>
                <mass value="0.055"/>
                <inertia ixx="1.1155878535842904e-05" ixy="0" ixz="0"
                        iyy="2.1057527828089415e-05" iyz="0"
                        izz="1.3568315958913178e-05"/>
        </inertial>
        </link>
        <joint name="servo_joint" type="fixed">
            <parent link="servo_base"/>
            <child link="servo"/>
            <origin xyz="0 -0.0185 ${0.00175 + 0.01}" rpy="0 0 0"/>
        </joint>
        <xacro:if value="${gazebo}">
            <gazebo reference="servo">
                <mu1>1.0</mu1>
                <mu2>1.0</mu2>
            </gazebo>
        </xacro:if>

        <!-- Link servo conn -->
        <link name="servo_conn">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
            <mesh filename="package://g_mov_description/meshes/servo_conn.stl" 
                scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="MetalGray"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
            <mesh filename="package://g_mov_description/meshes/servo_conn.stl" 
                scale="0.001 0.001 0.001"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0 " rpy="0 0 0"/>
                <mass value="0.0024"/>
                <inertia ixx="8.40345435933159e-08" ixy="0" ixz="0"
                        iyy="8.401908867990422e-08" iyz="0"
                        izz="1.5995363227322013e-07"/>
        </inertial>
        </link>
        <joint name="${joint_prefix}_servo_conn_joint" type="revolute">
            <parent link="servo"/>
            <child link="servo_conn"/>
            <limit lower="${-pi/4}" upper="${pi/6}" effort="1.0" velocity="1.0"/>
            <axis xyz="0.0 0.0 1.0"/>
            <origin xyz="0.01 0.042 0" rpy="${-pi/2} 0 0"/>
        </joint>
        <xacro:if value="${gazebo}">
            <gazebo reference="servo_conn">
                <mu1>1.0</mu1>
                <mu2>1.0</mu2>
            </gazebo>
        </xacro:if>

        <!-- Link Pi Cam Support -->
        <link name="picam_sup">
        <visual>
            <origin xyz="0 0 0" rpy="0 ${-pi/2} ${pi/2}"/>
            <geometry>
            <mesh filename="package://g_mov_description/meshes/picam_sup.stl" 
                scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="PLAGray"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 ${-pi/2} ${pi/2}"/>
            <geometry>
            <mesh filename="package://g_mov_description/meshes/picam_sup.stl" 
                scale="0.001 0.001 0.001"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0 " rpy="0 ${-pi/2} ${pi/2}"/>
                <mass value="0.008"/>
                <inertia ixx="2.2308333333333333e-06" ixy="0" ixz="0"
                        iyy="1.5268333333333331e-06" iyz="0"
                        izz="3.1123333333333332e-06"/>
        </inertial>
        </link>
        <joint name="picam_sup_joint" type="fixed">
            <parent link="servo_conn"/>
            <child link="picam_sup"/>
            <origin xyz="0 0 0.005" rpy="0 0 0"/>
        </joint>
        <xacro:if value="${gazebo}">
            <gazebo reference="picam_sup">
                <mu1>1.0</mu1>
                <mu2>1.0</mu2>
            </gazebo>
        </xacro:if>

        <!-- Link Pi Cam -->
        <link name="picam">
        <visual>
            <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
            <mesh filename="package://g_mov_description/meshes/picam.stl" 
                scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="RaspberryGreen"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
            <mesh filename="package://g_mov_description/meshes/picam.stl" 
                scale="0.001 0.001 0.001"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0 " rpy="0 ${pi/2} 0"/>
                <mass value="0.008"/>
                <inertia ixx="2.2308333333333333e-06" ixy="0" ixz="0"
                        iyy="1.5268333333333331e-06" iyz="0"
                        izz="3.1123333333333332e-06"/>
        </inertial>
        </link>
        <joint name="picam_joint" type="fixed">
            <parent link="picam_sup"/>
            <child link="picam"/>
            <origin xyz="0.038 -0.004 -0.0275" rpy="0 0 0"/>
        </joint>
        <xacro:if value="${gazebo}">
            <gazebo reference="picam_sup">
                <mu1>1.0</mu1>
                <mu2>1.0</mu2>
            </gazebo>
        </xacro:if>
        <!-- Camera reference -->
        <xacro:add_cam_links x="0.0065" y="-0.003" z="0" R="0" P="${pi/2}" Y="0"
          parent="picam"/>
    
        <xacro:if value="${gazebo}">
            <gazebo reference="g_mov_cam_link">
                <sensor name="camera" type="camera">
                    <!-- Data based on : -->
                    <!-- https://static.chipdip.ru/lib/664/DOC001664108.pdf -->
                    <camera>
                        <horizontal_fov>1.361357</horizontal_fov>
                        <image>
                        <width>1080</width>
                        <height>810</height>
                        </image>
                        <clip>
                            <near>0.2</near>
                            <far>10.0</far>
                        </clip>
                        <xacro:if value="true">
                            <!-- Noise addition -->
                            <noise>
                                <type>gaussian</type>
                                <mean>0.0</mean>
                                <stddev>0.015</stddev>
                            </noise>
                            <!-- Distorsion addition -->
                            <distortion>
                                <k1>-0.1</k1>
                                <k2>0.02</k2>
                                <k3>0.01</k3>
                                <p1>0.0</p1>
                                <p2>0.0</p2>
                                <center>0.5 0.5</center>
                            </distortion>
                        </xacro:if>
                    </camera>
                    <always_on>1</always_on>
                    <update_rate>30</update_rate>
                    <visualize>true</visualize>
                </sensor>
            </gazebo>
        </xacro:if>
    </xacro:macro>
</robot>