<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
<!--///////////////////// M3 x 10 SPACERS MACROS ///////////////////////-->

    <xacro:macro name="generic_spacer"
            params="id parent element front side x y z m xx xy xz yy yz zz">
        
        <!-- Link -->
        <link name="${id}_${element}_${front}${side}">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
            <mesh filename="package://g_mov_description/meshes/spacer_${id}.stl" 
                scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="Brass"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
            <mesh filename="package://g_mov_description/meshes/spacer_${id}.stl" 
                scale="0.001 0.001 0.001"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0 " rpy="0 0 0"/>
            <mass value="${m}"/>
            <inertia ixx="${xx}" ixy="${xy}" ixz="${xz}"
                    iyy="${yy}" iyz="${yz}"
                    izz="${zz}"/>
        </inertial>
        </link>

        <joint name="${id}_${element}_${front}${side}_joint" type="fixed">
            <parent link="${parent}"/>
            <child link="${id}_${element}_${front}${side}"/>
            <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
        </joint>
    </xacro:macro>

    <!-- 4 symetric hex spacers by considering x/y axis -->
    <xacro:macro name="x4xgeneric_spacer" 
                params="id element parent offset_x offset_y x y z">
        <xacro:spacer_m3x10 id="${id}" parent="${parent}" element="${element}" 
            front="f" side="r" x="${x + offset_x}" y="${y - offset_y}" z="${z}"/>
        <xacro:spacer_m3x10 id="${id}" parent="${parent}" element="${element}" 
            front="f" side="l" x="${x + offset_x}" y="${y + offset_y}" z="${z}"/>
        <xacro:spacer_m3x10 id="${id}" parent="${parent}" element="${element}" 
            front="r" side="r" x="${x - offset_x}" y="${y + offset_y}" z="${z}"/>
        <xacro:spacer_m3x10 id="${id}" parent="${parent}" element="${element}" 
            front="r" side="l" x="${x - offset_x}" y="${y - offset_y}" z="${z}"/>
    </xacro:macro>
</robot>